[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]

[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]

[language-server.vscode-html-language-server]
command = "vscode-html-language-server"
args = ["--stdio"]

[language-server.vscode-css-language-server]
command = "vscode-css-language-server"
args = ["--stdio"]

[language-server.rust-analyzer]
command = "rust-analyzer"

[[language]]
name = "python"
language-servers = ["basedpyright"]

[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]

[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]

[[language]]
name = "jsx"
language-servers = ["typescript-language-server"]

[[language]]
name = "tsx"
language-servers = ["typescript-language-server"]

[[language]]
name = "html"
language-servers = ["vscode-html-language-server"]

[[language]]
name = "css"
language-servers = ["vscode-css-language-server"]

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]
